### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by spadavec** [sysbio-vo/bnfinder#6] opened 2018-11-03 02:04 UTC
When using the most recent version of BNF I get the following error: 

```
Loading data from: bnfity.csv ...
Traceback (most recent call last):
  File "/home/spadavec/miniconda2/envs/rdkit/bin/bnf", line 4, in <module>
    __import__('pkg_resources').run_script('BNfinder==2.2.0', 'bnf')
  File "/home/spadavec/miniconda2/envs/rdkit/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/spadavec/miniconda2/envs/rdkit/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/home/spadavec/miniconda2/envs/rdkit/lib/python2.7/site-packages/BNfinder-2.2.0-py2.7.egg/EGG-INFO/scripts/bnf", line 45, in <module>
    
  File "build/bdist.linux-x86_64/egg/BNfinder/data.py", line 545, in fromNewFile
  File "build/bdist.linux-x86_64/egg/BNfinder/continuous.py", line 119, in estimate
  File "build/bdist.linux-x86_64/egg/BNfinder/stats.py", line 247, in __call__
  File "build/bdist.linux-x86_64/egg/BNfinder/stats.py", line 297, in lmean
ZeroDivisionError: float division by zero
```

Is this a known error? my CSV contains continuous expression values

**Comment by alnf** [comment] 2018-11-03 09:55
In order to answer your question I need to know the exact structure of your input file.

**Comment by spadavec** [comment] 2018-11-03 16:45
My apologies--the input file was too large to attach here so I forgot to mention it! 

The `shape` of the file is (35238, 759), but I've attached a link to a google doc thats a subset of this file:

https://docs.google.com/spreadsheets/d/1X1_hBpxYANQ8FDJmsaM47R6LgwDHm3P1esxwXzjQLq0/edit?usp=sharing

This just has the first 20 rows reported. Is it possible that the headers being int's is throwing things off? It appears that the variable `inlist` is returning either 0 or Null, but I can't be sure what this list is referring to.

**Comment by alnf** [comment] 2018-11-03 18:34
Since you posted Google spreadsheet, not the plain text, I cannot know for sure, however, the correct format is tab separated value, not comma separated value. Check the examples folder, for instance this file: https://github.com/sysbio-vo/bnfinder/blob/master/doc/data/input1.txt.

When I saved your file as tsv it worked just fine for me. I would strongly recommend you to read the user manual before you proceed - https://github.com/sysbio-vo/bnfinder/blob/master/doc/bnfinder_doc_all.pdf. I noticed you didn't supply regulators list, so is your data time series?

**Comment by alnf** [comment] 2018-11-15 19:56
So, did you succeed in running it?

**Comment by spadavec** [comment] 2018-11-16 01:45
[newsubset.txt](https://github.com/sysbio-vo/bnfinder/files/2587661/newsubset.txt)
I remade it tab separated, formatted based on input7.txt in your data file. reran it and iI'm still getting the same error.

**Comment by alnf** [comment] 2018-11-16 21:25
Hmm, it works for me. Can you please pass me the line how exactly you run it, and since you're running it within conda env, you might as well copy your environment and give to me, so I will try to reproduce. Could be smth with specific version of python.

**Comment by spadavec** [comment] 2018-11-25 02:37
```
(rdkit) spadavec@turing:/data1/bayesnet/bnfinder/doc/data$ conda list -n rdkit
# packages in environment at /home/spadavec/miniconda2/envs/rdkit:
#
absl-py                   0.1.10                    <pip>
alabaster                 0.7.10                   py27_1    conda-forge
ambermini                 16.16.0                       7    omnia
argparse                  1.2.1                     <pip>
asn1crypto                0.24.0                    <pip>
astroid                   1.6.1                     <pip>
babel                     2.5.3                    py27_0    conda-forge
backports                 1.0                      py27_1    conda-forge
backports.functools_lru_cache 1.5                      py27_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports.weakref         1.0.post1                 <pip>
backports_abc             0.5                      py27_0    conda-forge
bayesian-optimization     0.6.0                     <pip>
beautifulsoup4            4.6.0                     <pip>
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                     <pip>
bleach                    2.1.3                      py_0    conda-forge
bnet                      0.2                       <pip>
bokeh                     0.13.0                   py27_0    conda-forge
boost                     1.66.0                   py27_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
buzhug                    1.8                       <pip>
bzip2                     1.0.6                         3  
cairo                     1.14.6                        5    conda-forge
cairocffi                 0.7.2                    py27_1    conda-forge
certifi                   2016.2.28                py27_0  
certifi                   2018.1.18                 <pip>
cffi                      1.11.2                    <pip>
cffi                      1.11.2                   py27_0    conda-forge
cffi                      1.11.4                    <pip>
chembl-webresource-client 0.9.31                    <pip>
click                     6.7                       <pip>
clusterutils              0.3.1                    py27_0    omnia
configparser              3.5.0                    py27_0    conda-forge
configparser              3.5.0                     <pip>
cryptography              2.1.4                     <pip>
cuda90                    1.0                  h6433d27_0    pytorch
cudatoolkit               8.0                           3  
cudnn                     6.0.21                cuda8.0_0  
curl                      7.59.0                        0    conda-forge
cycler                    0.10.0                   py27_0    conda-forge
cython                    0.28.1                   py27_0    conda-forge
Cython                    0.23.4                    <pip>
dbus                      1.10.22                       0    conda-forge
decorator                 4.2.1                    py27_0    conda-forge
docopt                    0.6.2                    py27_0    conda-forge
docutils                  0.14                     py27_0    conda-forge
easydict                  1.7                       <pip>
entrypoints               0.2.3                    py27_1    conda-forge
enum34                    1.1.6                     <pip>
enum34                    1.1.6                    py27_1    conda-forge
expat                     2.2.5                         0    conda-forge
fftw3f                    3.3.4                         2    omnia
Flask                     0.12.2                    <pip>
fontconfig                2.12.1                        5    conda-forge
freetype                  2.7                           2    conda-forge
funcsigs                  1.0.2                     <pip>
functools32               3.2.3.2                  py27_2    conda-forge
futures                   3.2.0                     <pip>
futures                   3.2.0                    py27_0    conda-forge
GEOparse                  1.0.5                     <pip>
gettext                   0.19.8.1                      0    conda-forge
gevent                    1.2.2                     <pip>
gevent-openssl            1.2                       <pip>
glib                      2.51.4                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
graphite2                 1.3.11                        0    conda-forge
greenlet                  0.4.13                    <pip>
grequests                 0.2.0                     <pip>
gsl                       2.4             blas_openblash47a8a8e_1  [blas_openblas]  conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
h5py                      2.5.0                     <pip>
harfbuzz                  1.4.3                         0    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        2    conda-forge
html5lib                  0.9999999                 <pip>
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                          0    conda-forge
idna                      2.6                       <pip>
imagesize                 1.0.0                    py27_0    conda-forge
intel-openmp              2019.0                      118  
ipaddress                 1.0.19                    <pip>
ipykernel                 4.8.2                    py27_0    conda-forge
ipython                   5.5.0                    py27_0    conda-forge
ipython_genutils          0.2.0                    py27_0    conda-forge
ipywidgets                7.1.2                    py27_0    conda-forge
isort                     4.3.4                     <pip>
itsdangerous              0.24                      <pip>
jbig                      2.1                           0  
Jinja2                    2.10                      <pip>
jinja2                    2.10                     py27_0    conda-forge
joblib                    0.12.5                    <pip>
jpeg                      9b                            0  
jsonschema                2.6.0                    py27_1    conda-forge
jupyter                   1.0.0                    py27_0    conda-forge
jupyter_client            5.2.3                    py27_0    conda-forge
jupyter_console           5.2.0                    py27_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
Keras                     2.0.8                     <pip>
krb5                      1.14.2                        0    conda-forge
latexcodec                1.0.5                    py27_0    conda-forge
lazy-object-proxy         1.3.1                     <pip>
libffi                    3.2.1                         3    conda-forge
libgcc                    5.2.0                         0  
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libgpuarray               0.6.9                         0  
libiconv                  1.14                          0  
libnetcdf                 4.5.0                         3    conda-forge
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.30                        1  
libsodium                 1.0.15                        1    conda-forge
libssh2                   1.8.0                         2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.6                         3  
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.4                         0  
linecache2                1.0.0                     <pip>
lxml                      4.2.1                     <pip>
lzo                       2.10                          0    conda-forge
mako                      1.0.6                    py27_0  
Markdown                  2.6.11                    <pip>
markupsafe                1.0                      py27_0  
matplotlib                2.1.1                    py27_0    conda-forge
mccabe                    0.6.1                     <pip>
mdtraj                    1.9.1                    py27_1    conda-forge
mistune                   0.8.3                      py_0    conda-forge
mkl                       2019.0                      118  
mkl_fft                   1.0.6                    py27_0    conda-forge
mkl_random                1.0.1                    py27_0    conda-forge
mock                      2.0.0                     <pip>
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.0                    py27_0    conda-forge
mpich                     3.2.1                         0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py27_0    conda-forge
nccl                      1.3.4                 cuda8.0_1  
ncurses                   5.9                          10    conda-forge
netcdf4                   1.3.1                    py27_2    conda-forge
networkx                  1.11                      <pip>
nose                      1.3.7                    py27_1  
notebook                  5.4.1                    py27_0    conda-forge
numexpr                   2.6.4                    py27_1    conda-forge
numpy                     1.15.2          py27_blas_openblashd3ea46f_1  [blas_openblas]  conda-forge
numpy                     1.14.1                    <pip>
numpy-base                1.14.3           py27h0ea5e3f_1  
numpydoc                  0.7.0                    py27_0    conda-forge
olefile                   0.44                     py27_0  
openblas                  0.2.20                        8    conda-forge
openmm                    7.2.1                    py27_1    omnia
openmmtools               0.14.0                   py27_0    omnia
openmoltools              0.8.1                    py27_0    omnia
openssl                   1.0.2l                        0  
oset                      0.1.3                    py27_0    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.4           py27hf8a1672_0    conda-forge
pandoc                    2.1.3                         0    conda-forge
pandocfilters             1.4.1                    py27_0    conda-forge
pango                     1.40.4                        0    conda-forge
parmed                    2.7.3                    py27_1    omnia
pathlib2                  2.3.0                    py27_0    conda-forge
pbr                       3.1.1                     <pip>
pcre                      8.39                          0    conda-forge
pexpect                   4.4.0                    py27_0    conda-forge
pickleshare               0.7.4                    py27_0    conda-forge
pillow                    4.3.0                    py27_1    conda-forge
pip                       9.0.1                    py27_1  
pip                       18.1                      <pip>
pixman                    0.34.0                        0  
pomegranate               0.10.0                    <pip>
progressbar2              3.35.2                    <pip>
prompt_toolkit            1.0.15                   py27_0    conda-forge
protobuf                  3.5.1                     <pip>
ptyprocess                0.5.2                    py27_0    conda-forge
pybtex                    0.21                     py27_0    conda-forge
pybtex-docutils           0.2.1                    py27_0    conda-forge
pycairo                   1.16.3                   py27_0    conda-forge
pycparser                 2.18                     py27_0    conda-forge
pycparser                 2.18                      <pip>
pygments                  2.2.0                    py27_0    conda-forge
pygpu                     0.6.9                    py27_0  
pylint                    1.8.2                     <pip>
pymbar                    3.0.3                    py27_1    conda-forge
pyOpenSSL                 17.5.0                    <pip>
pyparsing                 2.2.0                    py27_0    conda-forge
pypdb                     1.103                     <pip>
pyqt                      5.6.0                    py27_4    conda-forge
pytables                  3.4.2                    py27_7    conda-forge
python                    2.7.13                        0  
python-dateutil           2.6.1                    py27_0  
pytorch                   0.3.0           py27cuda8.0cudnn6.0_0  
pytz                      2017.2                   py27_0  
pyyaml                    3.12                     py27_1    conda-forge
PyYAML                    3.12                      <pip>
pyzmq                     17.0.0                   py27_3    conda-forge
qt                        5.6.2                         6    conda-forge
qtconsole                 4.3.1                    py27_0    conda-forge
r                         3.4.1                  r3.4.1_0    conda-forge
r-base                    3.4.1                         2    conda-forge
r-boot                    1.3_20                 r3.4.1_0    conda-forge
r-class                   7.3_14                 r3.4.1_0    conda-forge
r-cluster                 2.0.6                  r3.4.1_0    conda-forge
r-codetools               0.2_15                 r3.4.1_0    conda-forge
r-foreign                 0.8_67                 r3.4.1_0    conda-forge
r-kernsmooth              2.23_15                r3.4.1_0    conda-forge
r-lattice                 0.20_34                r3.4.1_0    conda-forge
r-mass                    7.3_48                 r3.4.1_0    conda-forge
r-matrix                  1.2_14                 r3.4.1_0    conda-forge
r-mgcv                    1.8_17                 r3.4.1_0    conda-forge
r-nlme                    3.1_131                r3.4.1_0    conda-forge
r-nnet                    7.3_12                 r3.4.1_0    conda-forge
r-recommended             3.4.1                  r3.4.1_0    conda-forge
r-rpart                   4.1_13                 r3.4.1_0    conda-forge
r-spatial                 7.3_11                 r3.4.1_0    conda-forge
r-survival                2.40_1                 r3.4.1_0    conda-forge
rdkit                     Release_2017_09_3          py27_3    conda-forge
readline                  6.2                           2  
requests                  2.18.4                    <pip>
requests                  2.13.0                   py27_0    conda-forge
requests                  2.5.1                     <pip>
requests-cache            0.4.13                    <pip>
scandir                   1.7                      py27_0    conda-forge
schema                    0.6.2                    py27_0    omnia
scikit-learn              0.20.0          py27_blas_openblasha84fab4_201  [blas_openblas]  conda-forge
scipy                     1.1.0           py27_blas_openblash7943236_201  [blas_openblas]  conda-forge
seaborn                   0.8.1                     <pip>
send2trash                1.5.0                      py_0    conda-forge
setuptools                36.4.0                   py27_1  
setuptools                38.5.1                    <pip>
simplegeneric             0.8.1                    py27_0    conda-forge
singledispatch            3.4.0.3                   <pip>
singledispatch            3.4.0.3                  py27_0    conda-forge
sip                       4.18                     py27_1    conda-forge
six                       1.10.0                   py27_0  
six                       1.10.0                    <pip>
snowballstemmer           1.2.1                    py27_0    conda-forge
sphinx                    1.7.1                    py27_0    conda-forge
sphinxcontrib-bibtex      0.3.6                    py27_0    conda-forge
sphinxcontrib-websupport  1.0.1                    py27_0    conda-forge
sqlite                    3.13.0                        0  
statistics                1.0.3.5                   <pip>
subprocess32              3.2.7                    py27_0    conda-forge
tables                    3.4.2                     <pip>
tensorflow                1.5.0                     <pip>
tensorflow-gpu            1.5.0                     <pip>
tensorflow-tensorboard    1.5.1                     <pip>
terminado                 0.8.1                    py27_0    conda-forge
testpath                  0.3.1                    py27_0    conda-forge
theano                    0.7.2                    py27_0    omnia
tinydb                    3.5.0                     <pip>
tk                        8.5.18                        0  
torchvision               0.1.8                    py27_0  
tornado                   5.0.1                    py27_1    conda-forge
traceback2                1.4.0                     <pip>
traitlets                 4.3.2                    py27_0    conda-forge
typing                    3.6.4                    py27_0    conda-forge
unittest2                 1.1.0                     <pip>
unittest2six              0.0.0                     <pip>
urllib3                   1.22                      <pip>
wcwidth                   0.1.7                    py27_0    conda-forge
webencodings              0.5                      py27_0    conda-forge
Werkzeug                  0.14.1                    <pip>
wgetter                   0.7                       <pip>
wheel                     0.29.0                   py27_0  
widgetsnbextension        3.1.4                    py27_0    conda-forge
wrapt                     1.10.11                   <pip>
xmltodict                 0.11.0                    <pip>
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0  
yaml                      0.1.7                         0    conda-forge
yank                      0.17.0                   py27_0    omnia
yank-examples             1.1.0                         0    omnia
zeromq                    4.2.3                         2    conda-forge
zlib                      1.2.11                        0  
```

I am using python 2.6, and am running the `bnf` command a number of ways: 

`bnf -s MDL -e bnfinput.txt -n output.sif -c -txt outputmdl.txt`

and 

`bnf -e bnfinput.txt -n output.sif -c -txt outputmdl.txt`

and I've attached my environment here if you want to install everything.


[environment.yml.gz](https://github.com/sysbio-vo/bnfinder/files/2612775/environment.yml.gz)

**Comment by alnf** [comment] 2018-11-25 14:29
Are you sure it's python 2.6, in your env I see it's python 2.7.13.

But more importantly your launch arguments are not exactly correct. If you want output files with the suboptimal parents sets, network structure, and conditional probability, it should be:

`bnf -e bnfinput.txt -n output.sif -c outputcpd.txt -t output_plain.txt`

More precisely, it's either `-t` or `--txt`, and after `-c` there should be a file name.

Can you please try to run the simplest case with example input:

`bnf -e doc/data/input1.txt -n output.sif -v`

Also, how exactly did you install/launch bnfinder? Are you sure it's the latest version from github?

**Comment by spadavec** [comment] 2018-11-25 20:37
The output of the suggested command is just fine (`bnf -e doc/data/input1.txt -n output.sif -v`): 

```
Loading data from: bnfinder/doc/data/input1.txt ... done
Learning network  bnfinder/doc/data/input1.txt  with BDE scoring function
Learning parents of P1 ... 
----------------------------------------
done P1 
 Score 103.006928646 for parents set:
Time, secs:  0.000233173370361
----------------------------------------
Learning parents of P2 ... 
----------------------------------------
done P2 
 Score 102.549373015 for parents set:
Time, secs:  0.000213146209717
----------------------------------------
Learning parents of G1 ... Using algorithm 2

----------------------------------------
done G1 
 Score 102.892629619 for parents set:
Time, secs:  0.000603914260864
----------------------------------------
Learning parents of G2 ... Using algorithm 2

----------------------------------------
done G2 
 Score 82.6047443697 for parents set: P1
Time, secs:  0.000607013702393
----------------------------------------
Learning parents of G3 ... Using algorithm 2

----------------------------------------
done G3 
 Score 89.1708277229 for parents set: P2
Time, secs:  0.000598907470703
----------------------------------------
Learning parents of G4 ... Using algorithm 2

----------------------------------------
done G4 
 Score 64.3673283321 for parents set: P1 P2
Time, secs:  0.000597953796387
----------------------------------------
Total score of optimal network: 544.591831705
P1	+	G2
P1	+	G4
P2	-	G3
P2	+	G4

Network graph written to: output.sif
P1	+	G2
P1	+	G4
P2	-	G3
P2	+	G4
```

Thanks for correcting the invocation (I just tried copying directly from the tutorial). With the updated commands, I still get the same error, unfortunately. The version of BNF that I'm using is straight from the repo (I just cloned it again and installed via `python setup.py install`) and am still getting the same error.

**Comment by spadavec** [comment] 2018-11-25 21:40
It appears the issue might be that my dataset isn't labeled with each row corresponding to a gene. I will figure out a way to change this and try again.

**Comment by spadavec** [comment] 2018-11-26 03:26
It turns out I was incorrect. While my input file is indeed missing a column for gene names, introducing that doesn't fix the issue. 

EDIT: It appears that it's actually the number of rows that might be causing the issue. If I reduce the number of rows from ~35k to ~10 (for example), the job starts just fine. I'm not sure where the cutoff might be, but I can investigate more tomorrow and update here.

**Comment by spadavec** [comment] 2018-11-28 05:48
It's hard to nail down exactly, but it appears that there's a threshold around ~25k rows where this error gets thrown. I've gone through the data and it appears theres nothing special about any of the rows (e..g no NaNs or non _int_ or _float_ types). Not entirely sure what the issue is, but pruning the datatset down seems to fix the issue (in that it allows the job to start, but I have a feeling the computation time is on the order of months, giving the O notation)

**Comment by alnf** [comment] 2018-11-29 09:11
Can you give me the input file, which causes the issue. Because the one you sent before does not produce it to me. I mean newsubset.txt. Or it's the one you tried? I just want to fix dataset and then ask you to run it with different parameters, because it's hard to debug when I don't know the launch arguments exactly.

Regarding computation time. First of all, if you use time-series data it's ok to use it without regulators list, since you're inferring Dynamic Bayesian network then. But if you have perturbational data, you must supply regulators list. For example, if you're working with human you can just use the list of transcriptions factors, you just need to specify which genes in your expression matrix are the factors. Again, you can check example input files or manual for that.

If you copied wrong argument from the manual before, please, tell me the page in pdf file, I will correct the text.

If you have extremely huge table I would first recommend to filter out some genes, it does not make sense to supply non-expressed genes, they will just introduce noise. And since your number of experiments is usually much less than number of genes, it's hard to completely "separate" the noise from real signal. Second, use "-l" parameter to limit parents set size, you can start with "1" and see how much time does it take. Third use "-k" to specify number of cores for the parallelization.

**Comment by alnf** [comment] 2019-01-14 11:38
I'm closing this issue, please, re-open if you have more information.

**Closed as completed by alnf** 2019-01-14 11:38 UTC
